<?php
return [
    'productBigImageWidth'=> 1000,
    'productBigImageHeight'=> 1000,
    'productMediumImageWidth'=> 415,
    'productMediumImageHeight'=> 415,
    'productSmallImageWidth'=> 150,
    'productSmallImageHeight'=> 150,
    'colors' => [
        'white' => 'Белый',
        'ivory' => 'Айвори',
        'body' => 'Телесный',
        'beige' => 'Бежевый',
        'gray' => 'Серый',
        'graphite' => 'Графитовый',
        'black' => 'Черный',
        'red' => 'Красный',
        'burgundy' => 'Бордовый',
        'blue' => 'Синий',
        'pink' => 'Розовый',
        'eggplant' => 'Баклажановый',
        'mint' => 'Мятный',
        'green' => 'Зеленый',
        'emerald' => 'Изумрудный',
        'lightblue' => 'Голубой',
        'yellow' => 'Желтый',
        'orange' => 'Оранжевый',
        'brown' => 'Коричневый',
    ],
];