<?php
return [
    'productBigImageWidth'=> 1000,
    'productBigImageHeight'=> 1000,
    'productMediumImageWidth'=> 415,
    'productMediumImageHeight'=> 415,
    'productSmallImageWidth'=> 150,
    'productSmallImageHeight'=> 150,
    'colors' => [
        'white' => 'Белый',
        'black' => 'Черный',
        'powder' => 'Пудра',
        'emerald' => 'Изумруд',
        'garnet' => 'Гранат',
        'violet' => 'Лиловый',
        'lemony' => 'Лимонный',
        'silver' => 'Серебро',
        'gold' => 'Золото',
        'fuchsia' => 'Фукси',
        'sand' => 'Песочный',
        'blue' => 'Синий',
        'lightblue' => 'Голубой',
        'mint' => 'Мята',
        'red' => 'Красный',
        'burgundy' => 'Бордовый',
        'olive' => 'Олива',
        'pistachio' => 'Фисташковый',
        'cacao' => 'Какао',
    ],
];